services:
  php-fpm:
    build:
      context: .
      dockerfile: docker/common/php-fpm/Dockerfile
      tags:
        - ${REGISTRY}/laravel-php-fpm:${TAG}
        - ${REGISTRY}/laravel-php-fpm:latest
      target: production
    image: ${REGISTRY}/laravel-php-fpm
    volumes:
      - laravel_public:/var/www/public
      - laravel_storage:/var/www/storage:rw
    networks:
      - laravel
    healthcheck:
      test: ["CMD-SHELL", "php-fpm-healthcheck || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.hostname == ${DOCKER_NODE}
    secrets:
      - source: laravel_env
        target: /var/www/.env
        mode: 0400
        uid: '33'
        gid: '33'

  web:
    build:
      context: .
      dockerfile: ./docker/production/nginx/Dockerfile
      tags:
        - ${REGISTRY}/laravel-web:${TAG}
        - ${REGISTRY}/laravel-web:latest
    image: ${REGISTRY}/laravel-web
    volumes:
      - laravel_public:/var/www/public
      - laravel_storage:/var/www/storage:ro
    networks:
      - laravel
    ports:
      - 8001:80
    depends_on:
      - php-fpm
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.hostname == ${DOCKER_NODE}

networks:
  laravel:

volumes:
    laravel_public:
      external: true
    laravel_storage:
      external: true

secrets:
    laravel_env:
        external: true

# Local Variables:
# yaml-indent-offset: 2
# indent-tabs-mode: nil
# End:
